import{a as P,S as B,i as s}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const R="https://pixabay.com/api/",$="52296397-de86b3c84befd39f908867df6";async function m(r,t){const n={key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await P.get(R,{params:n})).data}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new B(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const t=r.map(({webformatURL:n,largeImageURL:a,tags:e,likes:o,views:c,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${c}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${q}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function f(){h.innerHTML=""}function L(){g.classList.add("visible")}function u(){g.classList.remove("visible")}function v(){y.classList.add("visible")}function d(){y.classList.remove("visible")}const w=document.querySelector(".form"),E=w.elements["search-text"],O=document.querySelector(".load-more");let l="",i=1,p=0;w.addEventListener("submit",async r=>{if(r.preventDefault(),l=E.value.trim(),i=1,!l){s.warning({message:"Please enter a search term!",position:"topRight"}),f(),d();return}f(),d(),L();try{const t=await m(l,i);if(u(),t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(t.hits),p=t.totalHits,i*15<p?v():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){u(),s.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}});O.addEventListener("click",async()=>{i+=1,d(),L();try{const r=await m(l,i);u(),b(r.hits),x(),i*15>=p?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch(r){u(),s.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}});function x(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
